### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/ferret#754]
**Describe the bug**
On fresh ferret install, I got `fatal error: unexpected signal during runtime execution` when I return JSON. 
Probably linked to: https://github.com/MontFerret/worker/issues/27

**To Reproduce**

- `go version go1.19 darwin/amd64`

- `go install github.com/MontFerret/cli/ferret@latest`3. 
<img width="1115" alt="Screenshot 2022-09-02 at 09 35 31" src="https://user-images.githubusercontent.com/6069599/188085579-26e85fbc-84bc-4e30-bfc3-ce04805fd4e2.png">

- `ferret exec  --browser-open test.yml`
> RETURN 0
<img width="415" alt="Screenshot 2022-09-02 at 09 35 49" src="https://user-images.githubusercontent.com/6069599/188086114-dba867b9-42ed-46a0-bafe-07b53837a5c6.png">

- `ferret exec  --browser-open test.yml`
> RETURN {'test': 0}
<img width="1222" alt="Screenshot 2022-09-02 at 09 49 59" src="https://user-images.githubusercontent.com/6069599/188086494-b9cea656-ba26-4367-a47c-65666c2c1aa3.png">

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1071705]

goroutine 1 [running]:
runtime.throw({0x1951176?, 0xc00031a0c0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000249190 sp=0xc000249160 pc=0x103649d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0xc0002491e0 sp=0xc000249190 pc=0x104c189
sync.(*Pool).Get(0x2117ca0)
	/usr/local/go/src/sync/pool.go:132 +0x25 fp=0xc000249218 sp=0xc0002491e0 pc=0x1071705
github.com/wI2L/jettison.encodeSortedMap(0x2117c60, {0xc0000c4000, 0x1, 0x1000}, {{0x1a7f2b8, 0xc00019a008}, {0x194ad2c, 0x23}, 0x5, 0x80, ...}, ...)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/w!i2!l/jettison@v0.7.3/encode.go:415 +0x7a fp=0xc000249358 sp=0xc000249218 pc=0x150c0ba
github.com/wI2L/jettison.encodeMap(0x0?, {0xc0000c4000, 0x0, 0x1000}, {{0x1a7f2b8, 0xc00019a008}, {0x194ad2c, 0x23}, 0x5, 0x80, ...}, ...)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/w!i2!l/jettison@v0.7.3/encode.go:364 +0x345 fp=0xc000249438 sp=0xc000249358 pc=0x150bc65
github.com/wI2L/jettison.newMapInstr.func1(0x2117ba0?, {0xc0000c4000?, 0xc00031eb90?, 0xc0000c4000?}, {{0x1a7f2b8, 0xc00019a008}, {0x194ad2c, 0x23}, 0x5, 0x80, ...})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/w!i2!l/jettison@v0.7.3/instruction.go:400 +0x72 fp=0xc0002494c8 sp=0xc000249438 pc=0x1511e52
github.com/wI2L/jettison.wrapInlineInstr.func1(0xc0003191d0, {0xc0000c4000?, 0xab389f8?, 0x40?}, {{0x1a7f2b8, 0xc00019a008}, {0x194ad2c, 0x23}, 0x5, 0x80, ...})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/w!i2!l/jettison@v0.7.3/instruction.go:406 +0x65 fp=0xc000249538 sp=0xc0002494c8 pc=0x1512065
github.com/wI2L/jettison.marshalJSON({0x180ea20?, 0xc0003191d0?}, {{0x1a7f2b8, 0xc00019a008}, {0x194ad2c, 0x23}, 0x5, 0x80, 0x0, 0x0})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/w!i2!l/jettison@v0.7.3/json.go:167 +0xd9 fp=0xc000249600 sp=0xc000249538 pc=0x1513019
github.com/wI2L/jettison.MarshalOpts({0x180ea20, 0xc0003191d0}, {0xc0002496e8, 0x1, 0x187e540?})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/w!i2!l/jettison@v0.7.3/json.go:142 +0x1a9 fp=0xc0002496c0 sp=0xc000249600 pc=0x1512e09
github.com/MontFerret/ferret/pkg/runtime/values.(*Object).MarshalJSON(0xc000318f30?)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/ferret@v0.16.6/pkg/runtime/values/object.go:47 +0x45 fp=0xc000249700 sp=0xc0002496c0 pc=0x151f905
github.com/MontFerret/ferret/pkg/runtime.(*Program).Run(0xc000318f90, {0x1a7f328, 0xc000318ff0}, {0xc000249910?, 0x0?, 0x0?})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/ferret@v0.16.6/pkg/runtime/program.go:99 +0x366 fp=0xc0002498a8 sp=0xc000249700 pc=0x1526ea6
github.com/MontFerret/cli/runtime.(*Builtin).Run(0xc00004a300, {0x1a7f328, 0xc0000b0000}, {0xc00003e498?, 0x1a77c00?}, 0x0?)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/runtime/builtin.go:55 +0x174 fp=0xc000249930 sp=0xc0002498a8 pc=0x17020f4
github.com/MontFerret/cli/runtime.Run({0x1a7f328, 0xc0000b0000}, {{0x192b904, 0x7}, {0x1a77c00, 0x0}, {0x1a77c00, 0x0}, 0x0, 0x0, ...}, ...)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/runtime/runtime.go:40 +0xaa fp=0xc0002499a8 sp=0xc000249930 pc=0x1703bca
github.com/MontFerret/cli/cmd.execScript(0xc0001acec0?, {{0x192b904, 0x7}, {0x1a77c00, 0x0}, {0x1a77c00, 0x0}, 0x0, 0x0, 0x0, ...}, ...)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/cmd/exec.go:131 +0x6e fp=0xc000249a60 sp=0xc0002499a8 pc=0x172c2ae
github.com/MontFerret/cli/cmd.ExecCommand.func2(0xc0002c3900, {0xc00009a080, 0x1, 0x2?})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/cmd/exec.go:110 +0x4d1 fp=0xc000249cd0 sp=0xc000249a60 pc=0x172b8d1
github.com/spf13/cobra.(*Command).execute(0xc0002c3900, {0xc0001ac020, 0x2, 0x2})
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c fp=0xc000249da8 sp=0xc000249cd0 pc=0x11d7e1c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c2a00)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd fp=0xc000249e60 sp=0xc000249da8 pc=0x11d849d
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
main.main()
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/ferret/main.go:70 +0x449 fp=0xc000249f80 sp=0xc000249e60 pc=0x172d409
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000249fe0 sp=0xc000249f80 pc=0x1038cb2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000249fe8 sp=0xc000249fe0 pc=0x10675c1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007afb0 sp=0xc00007af90 pc=0x1039076
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc00007afe0 sp=0xc00007afb0 pc=0x1038f0d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007afe8 sp=0xc00007afe0 pc=0x10675c1
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007b790 sp=0xc00007b770 pc=0x1039076
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc00007b7c8 sp=0xc00007b790 pc=0x1026037
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00007b7e0 sp=0xc00007b7c8 pc=0x101ac86
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007b7e8 sp=0xc00007b7e0 pc=0x10675c1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000a4000?, 0x1a77c38?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007bf70 sp=0xc00007bf50 pc=0x1039076
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x2118720)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00007bfa0 sp=0xc00007bf70 pc=0x1024093
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:622 +0x65 fp=0xc00007bfc8 sp=0xc00007bfa0 pc=0x1024685
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00007bfe0 sp=0xc00007bfc8 pc=0x101ac26
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007bfe8 sp=0xc00007bfe0 pc=0x10675c1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x19b8750?, 0x0?, 0x60?, 0x2000000020?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007a628 sp=0xc00007a608 pc=0x1039076
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00007a7e0 sp=0xc00007a628 pc=0x1019d8f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007a7e8 sp=0xc00007a7e0 pc=0x10675c1
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 19 [select, locked to thread]:
runtime.gopark(0xc0000767a8?, 0x2?, 0xf7?, 0x93?, 0xc0000767a4?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000114e20 sp=0xc000114e00 pc=0x1039076
runtime.selectgo(0xc000114fa8, 0xc0000767a0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc000114f60 sp=0xc000114e20 pc=0x10483fc
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:991 +0x187 fp=0xc000114fe0 sp=0xc000114f60 pc=0x104c5e7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000114fe8 sp=0xc000114fe0 pc=0x10675c1
created by runtime.ensureSigM
	/usr/local/go/src/runtime/signal_unix.go:974 +0xbd

goroutine 5 [syscall]:
runtime.sigNoteSleep(0x0)
	/usr/local/go/src/runtime/os_darwin.go:123 +0x1e fp=0xc00007c7a0 sp=0xc00007c768 pc=0x103347e
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:149 +0x28 fp=0xc00007c7c0 sp=0xc00007c7a0 pc=0x1063948
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19 fp=0xc00007c7e0 sp=0xc00007c7c0 pc=0x10f1259
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007c7e8 sp=0xc00007c7e0 pc=0x10675c1
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 6 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007cef8 sp=0xc00007ced8 pc=0x1039076
runtime.chanrecv(0xc0001a65a0, 0x0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49b fp=0xc00007cf88 sp=0xc00007cef8 pc=0x10081bb
runtime.chanrecv1(0x0?, 0x0?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc00007cfb0 sp=0xc00007cf88 pc=0x1007cb8
main.main.func3()
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/ferret/main.go:65 +0x2d fp=0xc00007cfe0 sp=0xc00007cfb0 pc=0x172d46d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007cfe8 sp=0xc00007cfe0 pc=0x10675c1
created by main.main
	/Users/pbrisorgueil/Documents/Dev/go/pkg/mod/github.com/!mont!ferret/cli@v1.8.0/ferret/main.go:63 +0x3de

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032a750 sp=0xc00032a730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032a7e0 sp=0xc00032a750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032a7e8 sp=0xc00032a7e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x2121580?, 0xc00007df88?, 0xe5?, 0x31?, 0xc000007d40?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007df50 sp=0xc00007df30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00007dfe0 sp=0xc00007df50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x6f188fe939b55?, 0x3?, 0x1e?, 0xb1?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007d750 sp=0xc00007d730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00007d7e0 sp=0xc00007d750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007d7e8 sp=0xc00007d7e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 20 [IO wait]:
runtime.gopark(0x5?, 0xc0002d8000?, 0x0?, 0x10?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000088af8 sp=0xc000088ad8 pc=0x1039076
runtime.netpollblock(0x107a129?, 0x1087f97?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:526 +0xf7 fp=0xc000088b30 sp=0xc000088af8 pc=0x10322f7
internal/poll.runtime_pollWait(0xab11f08, 0x72)
	/usr/local/go/src/runtime/netpoll.go:305 +0x89 fp=0xc000088b50 sp=0xc000088b30 pc=0x1061949
internal/poll.(*pollDesc).wait(0xc000334000?, 0xc0002d8000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000088b78 sp=0xc000088b50 pc=0x10cfdb2
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000334000, {0xc0002d8000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a fp=0xc000088bf8 sp=0xc000088b78 pc=0x10d111a
net.(*netFD).Read(0xc000334000, {0xc0002d8000?, 0x0?, 0x4?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29 fp=0xc000088c40 sp=0xc000088bf8 pc=0x1112149
net.(*conn).Read(0xc0001a4178, {0xc0002d8000?, 0xc00031c018?, 0x1?})
	/usr/local/go/src/net/net.go:183 +0x45 fp=0xc000088c88 sp=0xc000088c40 pc=0x1120085
net/http.(*persistConn).Read(0xc000332000, {0xc0002d8000?, 0x1049180?, 0xc000088ec8?})
	/usr/local/go/src/net/http/transport.go:1929 +0x4e fp=0xc000088ce8 sp=0xc000088c88 pc=0x132af2e
bufio.(*Reader).fill(0xc0001a66c0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff fp=0xc000088d20 sp=0xc000088ce8 pc=0x11828bf
bufio.(*Reader).Peek(0xc0001a66c0, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d fp=0xc000088d40 sp=0xc000088d20 pc=0x1182a1d
net/http.(*persistConn).readLoop(0xc000332000)
	/usr/local/go/src/net/http/transport.go:2093 +0x1ac fp=0xc000088fc8 sp=0xc000088d40 pc=0x132bd4c
net/http.(*Transport).dialConn.func5()
	/usr/local/go/src/net/http/transport.go:1751 +0x26 fp=0xc000088fe0 sp=0xc000088fc8 pc=0x132a526
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000088fe8 sp=0xc000088fe0 pc=0x10675c1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x173e

goroutine 21 [select]:
runtime.gopark(0xc000110f90?, 0x2?, 0xd8?, 0xd?, 0xc000110f24?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000110d90 sp=0xc000110d70 pc=0x1039076
runtime.selectgo(0xc000110f90, 0xc000110f20, 0xc0001acf80?, 0x0, 0xc00027efc0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc000110ed0 sp=0xc000110d90 pc=0x10483fc
net/http.(*persistConn).writeLoop(0xc000332000)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5 fp=0xc000110fc8 sp=0xc000110ed0 pc=0x132d9d5
net/http.(*Transport).dialConn.func6()
	/usr/local/go/src/net/http/transport.go:1752 +0x26 fp=0xc000110fe0 sp=0xc000110fc8 pc=0x132a4c6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000110fe8 sp=0xc000110fe0 pc=0x10675c1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1752 +0x1791

goroutine 36 [GC worker (idle)]:
runtime.gopark(0xc0003260c0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000076f50 sp=0xc000076f30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000076fe0 sp=0xc000076f50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x4?, 0xc000314020?, 0xe?, 0x0?, 0xc0001c3700?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032e750 sp=0xc00032e730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032e7e0 sp=0xc00032e750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032e7e8 sp=0xc00032e7e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032af50 sp=0xc00032af30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032afe0 sp=0xc00032af50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032afe8 sp=0xc00032afe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032ef50 sp=0xc00032ef30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032efe0 sp=0xc00032ef50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032efe8 sp=0xc00032efe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032f750 sp=0xc00032f730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032f7e0 sp=0xc00032f750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032f7e8 sp=0xc00032f7e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 14 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032b750 sp=0xc00032b730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032b7e0 sp=0xc00032b750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032b7e8 sp=0xc00032b7e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 15 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032bf50 sp=0xc00032bf30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032bfe0 sp=0xc00032bf50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032bfe8 sp=0xc00032bfe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 40 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032ff50 sp=0xc00032ff30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032ffe0 sp=0xc00032ff50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032ffe8 sp=0xc00032ffe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x6f188fe93942c?, 0x3?, 0x9f?, 0x67?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000077750 sp=0xc000077730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000777e0 sp=0xc000077750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000777e8 sp=0xc0000777e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 24 [GC worker (idle)]:
runtime.gopark(0x2153dc0?, 0x1?, 0x7?, 0xcd?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000077f50 sp=0xc000077f30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000077fe0 sp=0xc000077f50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x6f188fe93cee5?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000078750 sp=0xc000078730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000787e0 sp=0xc000078750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 16 [GC worker (idle)]:
runtime.gopark(0x6f188fe939a5a?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00032c750 sp=0xc00032c730 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00032c7e0 sp=0xc00032c750 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00032c7e8 sp=0xc00032c7e0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 26 [GC worker (idle)]:
runtime.gopark(0x6f188fe939437?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000078f50 sp=0xc000078f30 pc=0x1039076
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000078fe0 sp=0xc000078f50 pc=0x101cdd1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x10675c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25
```

**Expected behavior**
No error 

**Desktop (please complete the following information):**
Mac intel, ferret browser, latest

**Additional context**
strangely it works fine with binaries already made

**Comment by ziflex** [comment]
Hmmm.
For some reason, jettison is causing the panic.

I will look into it.
Could you provide an example of a JSON value you are returning?

**Comment by PierreBrisorgueil** [comment]
Hey 👋,

Yes, it's just like in my previous post:  `RETURN {'test': 0}` in the .fql is sufficient to reproduce the bug 

<img width="948" alt="Screenshot 2022-10-10 at 10 27 54" src="https://user-images.githubusercontent.com/6069599/194825749-ef868171-a8ec-40c9-b8ff-e400c82fbf6b.png">

**Comment by ziflex** [comment]
Hey, can you try this with the latest version?

**Comment by PierreBrisorgueil** [comment]
I will try asap, it was fixed on my worker with 

`replace github.com/wI2L/jettison v0.7.3 => github.com/wI2L/jettison v0.7.4`
